# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
<<<<<<< HEAD
source:         "."
destination:    ./_gh_pages
port:           9001
baseurl:        ""
url:            "https://getbootstrap.com"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - nuget/
  - scss/
  - vendor/
  - bower.json
  - composer.json
  - Gemfile
  - Gemfile.lock
  - package.js
  - package.json
  - package-lock.json
  - sache.json
  - twbsconfig.yml

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              Bootstrap
description:        "The most popular HTML, CSS, and JS library in the world."
twitter:            getbootstrap
authors:            "Mark Otto, Jacob Thornton, and Bootstrap contributors"
social_image_path:  /assets/brand/bootstrap-social.png
social_logo_path:   /assets/brand/bootstrap-social-logo.png

# Custom variables
current_version:    4.0.0-beta
docs_version:       4.0
repo:               "https://github.com/twbs/bootstrap"
slack:              "https://bootstrap-slack.herokuapp.com"
blog:               "https://blog.getbootstrap.com"
expo:               "https://expo.getbootstrap.com"
jobs:               "https://jobs.getbootstrap.com"
themes:             "https://themes.getbootstrap.com"

download:
  source:           "https://github.com/twbs/bootstrap/archive/v4.0.0-beta.zip"
  dist:             "https://github.com/twbs/bootstrap/releases/download/v4.0.0-beta/bootstrap-4.0.0-beta-dist.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
  css_hash:         "sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
  js:               "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
  js_hash:          "sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
  jquery:           "https://code.jquery.com/jquery-3.2.1.slim.min.js"
  jquery_hash:      "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
  popper_hash:      "sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh"
=======
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          ""
url:              http://getbootstrap.com
encoding:         UTF-8

gems:
  - jekyll-sitemap

# Custom vars
current_version:  3.3.7
docs_version:     3.3
repo:             https://github.com/twbs/bootstrap
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.3.7.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.3.7.tar.gz

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com
themes:           http://themes.getbootstrap.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
  css_hash:       "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
  css_theme:      https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css
  css_theme_hash: "sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js
  js_hash:        "sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
>>>>>>> upstream/master
