# Dependencies
markdown:         rdiscount
pygments:         false

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

exclude:
  - "jade"
  - "vendor"

# Custom vars
current_version:  3.1.1-m4
repo:             https://github.com/mantacode/bootstrap
sass_repo:        https://github.com/mantacode/bootstrap-sass

download:
  source:         https://github.com/mantacode/bootstrap/archive/v3.1.1-m4.zip
  dist:           https://github.com/mantacode/bootstrap/releases/download/v3.1.1-m4/bootstrap-3.1.1-m4-dist.zip
  sass:           https://github.com/mantacode/bootstrap-sass/archive/v3.1.1-m4.tar.gz

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1-m4/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.1-m4/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.1-m4/js/bootstrap.min.js
