# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]
port:             9001

# Custom vars
current_version:  3.1.0
repo:             https://github.com/twbs/bootstrap

download_source:  https://github.com/twbs/bootstrap/archive/v3.1.0.zip
download_dist:    https://github.com/twbs/bootstrap/releases/download/v3.1.0/bootstrap-3.1.0-dist.zip
download_sass:    https://github.com/twbs/bootstrap-sass/archive/v3.1.0.0.tar.gz

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css
cdn_theme_css:    //netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap-theme.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js
