# Dependencies
markdown:     rdiscount
pygments:     true

# Permalinks
permalink:    pretty

# Server
destination:  ./_gh_pages
exclude:      [".editorconfig", ".gitignore", ".ruby-version", "bower.json", "composer.json", "CONTRIBUTING.md", "LICENSE", "Makefile", "package.json", "node_modules", "README.md", "less"]
port:         9001
