# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           ./docs
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001
encoding:         UTF-8

exclude:          ["vendor"]

# Custom vars
current_version:  3.0.3
repo:             https://github.com/twbs/bootstrap
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.0.3.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.0.3/bootstrap-3.0.3-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.0.3.0.tar.gz

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js
