title:                  "Bootstrap"
baseURL:                "https://getbootstrap.com"

docsDir:                "site"

subtitle:               "The most popular HTML, CSS, and JS library in the world."
description:            "Powerful, extensible, and feature-packed frontend toolkit. Build and customize with Sass, utilize prebuilt grid system and components, and bring projects to life with powerful JavaScript plugins."
authors:                "Mark Otto, Jacob Thornton, and Bootstrap contributors"

current_version:        "5.3.8"
current_ruby_version:   "5.3.8"
docs_version:           "5.3"
rfs_version:            "v10.0.0"
github_org:             "https://github.com/twbs"
repo:                   "https://github.com/twbs/bootstrap"
x:                      "getbootstrap"
opencollective:         "https://opencollective.com/bootstrap"
blog:                   "https://blog.getbootstrap.com/"
icons:                  "https://icons.getbootstrap.com/"
swag:                   "https://cottonbureau.com/people/bootstrap"

analytics:
  fathom_site:          "ITUSEYJG"

algolia:
  app_id:                "AK7KMZKZHQ"
  api_key:               "3151f502c7b9e9dafd5e6372b691a24e"
  index_name:            "bootstrap"

download:
  source:               "https://github.com/twbs/bootstrap/archive/v5.3.8.zip"
  dist:                 "https://github.com/twbs/bootstrap/releases/download/v5.3.8/bootstrap-5.3.8-dist.zip"
  dist_examples:        "https://github.com/twbs/bootstrap/releases/download/v5.3.8/bootstrap-5.3.8-examples.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:                  "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
  css_hash:             "sha384-TDmpFhAO5TwSQwPF95I/odgwpTUuv0aaVm9/0fL7b+kKe7hFBp/+9cBCMkydgGOi"
  js:                   "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.min.js"
  js_hash:              "sha384-Php492snRLTR5p+hMyxpV6gYwp1avWXn4AaX31MgANrvsjr9Dpodl3Nw60L7Pewl"
  js_bundle:            "https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
  js_bundle_hash:       "sha384-I2J4jlw924JZXHU9un9Mcuixq/rKhd5A8/B1NQ6ifPAiBFacZjwNcec8d6L38jQv"
  floating_ui:          "https://cdn.jsdelivr.net/npm/@floating-ui/dom@1.7.0/dist/floating-ui.dom.umd.min.js"
  floating_ui_hash:     "sha384-R7p1RqabZNhI+RdPNIzTouzd/LBVorZ0Tn3ApcogSOk+HF3o+P0HIenrUw/n0MOj"
  floating_ui_esm:      "https://cdn.jsdelivr.net/npm/@floating-ui/dom@1.7.0/dist/floating-ui.dom.esm.min.js"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  6
