# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "XhmikosR"
    default_labels:
      - "dependencies"
      - "v5"
    version_requirement_updates: "increase_versions"
