# https://dependabot.com/docs/config-file/
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "v4-dev"
    default_reviewers:
      - "XhmikosR"
    default_labels:
      - "dependencies"
      - "v4"
    version_requirement_updates: "increase_versions"
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "v4-dev"
    default_reviewers:
      - "XhmikosR"
    default_labels:
      - "dependencies"
      - "v4"
    version_requirement_updates: "increase_versions"
