languageCode:           "en"
title:                  "Bootstrap"
baseURL:                "http://127.0.0.1:9001"

pygmentsUseClasses:     true

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

publishdir:             "../_gh_pages"
archetypedir:           "archetypes"
contentdir:             "content"
dataDir:                "data"
layoutdir:              "layouts"
staticdir:              "static"
themesdir:              "themes"

ignoreFiles:
  - .git/
  - .github/
  - assets/scss/
  - build/
  - js/
  - node_modules/
  - nuget/
  - scss/
  - bower.json
  - composer.json
  - package.js
  - package.json
  - package-lock.json
  - sache.json

googleAnalytics:        "UA-146052-10"

social:
  twitter:              "getbootstrap"

params:
  description:          "The most popular HTML, CSS, and JS library in the world."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /assets/brand/bootstrap-social.png
  social_logo_path:     /assets/brand/bootstrap-social-logo.png

  current_version:      "4.0.0-beta.2"
  current_ruby_version: "4.0.0.beta2"
  docs_version:         "4.0"
  repo:                 "https://github.com/twbs/bootstrap"
  slack:                "https://bootstrap-slack.herokuapp.com"
  blog:                 "https://blog.getbootstrap.com"
  expo:                 "https://expo.getbootstrap.com"
  jobs:                 "https://jobs.getbootstrap.com"
  themes:               "https://themes.getbootstrap.com"

  download:
    source:             "https://github.com/twbs/bootstrap/archive/v4.0.0-beta.2.zip"
    dist:               "https://github.com/twbs/bootstrap/releases/download/v4.0.0-beta.2/bootstrap-4.0.0-beta.2-dist.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:                "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
    css_hash:           "sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb"
    js:                 "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
    js_hash:            "sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
    jquery:             "https://code.jquery.com/jquery-3.2.1.slim.min.js"
    jquery_hash:        "sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    popper:             "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"
    popper_hash:        "sha384-W1IgCZfiFCplncoIxD5rld+uzdB6FlcG2vm4qjrCP5Z7uUt7vnwbztJXeqXgd26w"
